version: '3.8'

services:
  # Backend API Service (FastAPI)
  backend_api_service:
    build:
      context: . # Build context is the project root
      dockerfile: ./Backend/Dockerfile # Specify path to Dockerfile
    container_name: tnsp_backend_api
    environment:
      - MASTER_API_KEY=${MASTER_API_KEY:-super-secret-dev-key}
    command: poetry run uvicorn App.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./Backend:/app # Mount for hot-reloading in development
    expose:
      - "8000"

  # Frontend UI Service (React)
  frontend_ui_service:
    build:
      context: . # Build context is the project root
      dockerfile: ./Frontend/Dockerfile # Specify path to Dockerfile
    container_name: tnsp_frontend_ui
    expose:
      - "80"

  # NGINX Reverse Proxy - The main entry point for all traffic
  nginx_reverse_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: tnsp_reverse_proxy
    ports:
      - "80:80"
    depends_on:
      - backend_api_service
      - frontend_ui_service
