name: TNSP CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_backend_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install backend dependencies
      working-directory: ./backend
      run: poetry install

    - name: Run backend tests with Pytest
      working-directory: ./backend
      run: poetry run pytest

  test_frontend_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run frontend linter
      working-directory: ./frontend
      run: npm run lint

  build_and_push_docker_images:
    # This job only runs on pushes to the main branch after tests have passed
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test_backend_service, test_frontend_service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: your-dockerhub-username/tnsp-backend:latest

      - name: Build and push Frontend UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: your-dockerhub-username/tnsp-frontend:latest
